# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import codecs
import json

from draftjs_exporter.html import HTML

from draftjs_exporter_markdown import BLOCK_MAP, ENGINE, ENTITY_DECORATORS, STYLE_MAP

content_state = {}

# Demo content from https://github.com/springload/draftjs_exporter/blob/master/example.py.
with open('docs/example.json') as example:
    content_state = json.load(example)

if __name__ == '__main__':
    # Initialise the exporter.
    exporter = HTML({
        # Those configurations are overridable like for draftjs_exporter.
        'block_map': BLOCK_MAP,
        'style_map': STYLE_MAP,
        'entity_decorators': ENTITY_DECORATORS,
        'engine': ENGINE,
    })

    markup = exporter.render(content_state)

    print(markup)

    # Output to a Markdown file to showcase the output in GitHub (and see changes in git).
    with codecs.open('docs/example.txt', 'w', 'utf-8') as file:
        file.write(
            """# Example output (generated by [`example.py`](../example.py))

---

{markdown}---
""".format(markdown=markup))
